### ISSUE TITLE
When I execute train.py I get the following error: NameError: nane 'myModel' is not defined

### ISSUE THREAD

**Issue by longlizhi** [mkang315/CST-YOLO#1]
Traceback(most recent call last): 
File "/home/hndx/llz/CST-YOLO-main/train. py", line 623, in <module>
    train(hyp, opt, device, tb_writer)
File"/home/hndx/llz/CST-YOLO-main/train. py", line 97, in train 
    model=Model(opt. cfg, ch=3, nc=nc, anchors=hyp. get(' anchors')). to(device)# create
File"/home/hndx/llz/CST-YOLO-main/models/yolopy", Line 528, in__init__
   self. model, self. save=parse._model(deepcopy(seLf. yamt), ch=[ ch])# model, savelist 
File "/nome/hndx/llz/CST-YOLO-main/models/yolo . py", tine 761, in parse_model 
   Aatten, myModel, myWinTR]:
 NameError: name ' myModel' is not defined

**Comment by mkang315** [comment]
Sorry for this bug. I've updated the yolo.py, please download new source code.

**Comment by longlizhi** [comment]
> Sorry for this bug. I've updated the yolo.py, please download new source code.

Hello author, may I ask if the superiority of your network over the source network yolov7 is only shown in big data? Because when I trained in the data set with only 90 pictures, the result was much worse than that of yolov7 (yolov7's F1 is 0.75, while the author's F1 of your network is 0.43)

**Comment by mkang315** [comment]
Thank you for testing our model CST-YOLO. The evaluation metrics of the object detection task are mAP, AP50:95, etc. We don't consider F1 as an evaluation metric.

**Comment by mkang315** [comment]
> > Sorry for this bug. I've updated the yolo.py, please download new source code.
> 
> Hello author, may I ask if the superiority of your network over the source network yolov7 is only shown in big data? Because when I trained in the data set with only 90 pictures, the result was much worse than that of yolov7 (yolov7's F1 is 0.75, while the author's F1 of your network is 0.43)

Thank you for testing our model CST-YOLO. The evaluation metrics of the object detection task are mAP, AP50:95, etc. We don't consider F1 as an evaluation metric.

**Comment by longlizhi** [comment]
Using the author's updated code to train in my data set, the training results of the author's proposed network are indeed worse than those of the source network yolov7, including the mAP@0.5 result mentioned by the author

**Comment by mkang315** [comment]
> Using the author's updated code to train in my data set, the training results of the author's proposed network are indeed worse than those of the source network yolov7, including the mAP@0.5 result mentioned by the author

Which dataset did you use? Does your dataset include small objects? What is your running environment?

**Comment by longlizhi** [comment]
自己制作的数据集，主要是小对象，运行环境与yolov7一致。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月20日(星期四) 晚上10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane &#39;myModel&#39; is not defined (Issue #1)






***@***.***作者提到的结果

您使用的是哪个数据集？您的数据集包括小对象吗？你的运行环境是怎样的？

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by mkang315** [comment]
> 自己制作的数据集，主要是小对象，运行环境与yolov7一致。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月20日(星期四) 晚上10:18 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane &#39;myModel&#39; is not defined (Issue #1) ***@***.***作者提到的结果 您使用的是哪个数据集？您的数据集包括小对象吗？你的运行环境是怎样的？ — 直接回复此邮件，在GitHub上查看，或者取消订阅. ***@***.***与&gt;.

Is your dataset publicly available? Or you could send it to me. CST-YOLO aims to blood cell detection. It isn't very strange that the performance of CST-YOLO is worse than YOLOv7 on other datasets. Also, our running environments are different from yours.

**Comment by longlizhi** [comment]
抱歉，数据集还没公开，但是你可以尝试一下，邮件发给你，注意查收，你可以试试，然后麻烦你告诉我结果



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月20日(星期四) 晚上10:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane &#39;myModel&#39; is not defined (Issue #1)





  
自己制作的数据集，主要是小对象，运行环境与yolov7一致。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年7月20日(星期四) 晚上10:18 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane 'myModel' is not defined (Issue #1) @.***作者提到的结果 您使用的是哪个数据集？您的数据集包括小对象吗？你的运行环境是怎样的？ — 直接回复此邮件，在GitHub上查看，或者取消订阅. @.***与&gt;.
  
Is your dataset publicly available? Or you could send it to me. CST-YOLO aims to blood cell detection. It isn't very strange that the performance of CST-YOLO is worse than YOLOv7 on other datasets. Also, our running environments are different from yours.

**Comment by mkang315** [comment]
> 抱歉，数据集还没公开，但是你可以尝试一下，邮件发给你，注意查收，你可以试试，然后麻烦你告诉我结果
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月20日(星期四) 晚上10:27 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane &#39;myModel&#39; is not defined (Issue #1) 自己制作的数据集，主要是小对象，运行环境与yolov7一致。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年7月20日(星期四) 晚上10:18 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane 'myModel' is not defined (Issue #1) @.***作者提到的结果 您使用的是哪个数据集？您的数据集包括小对象吗？你的运行环境是怎样的？ — 直接回复此邮件，在GitHub上查看，或者取消订阅. @.***与&gt;. Is your dataset publicly available? Or you could send it to me. CST-YOLO aims to blood cell detection. It isn't very strange that the performance of CST-YOLO is worse than YOLOv7 on other datasets. Also, our running environments are different from yours. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Please send the download link (e.g. pan.baidu.com) to ******@*****.com. Is the dataset annotated manually? Have you divided the train and test sets? I'll evaluate CST-YOLO and YOLOv7 and find the reason why not effective on your dataset.

**Comment by longlizhi** [comment]
***@***.***邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月20日(星期四) 晚上10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane &#39;myModel&#39; is not defined (Issue #1)





  
抱歉，数据集还没公开，但是你可以尝试一下，邮件发给你，注意查收，你可以试试，然后麻烦你告诉我结果
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年7月20日(星期四) 晚上10:27 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane 'myModel' is not defined (Issue #1) 自己制作的数据集，主要是小对象，运行环境与yolov7一致。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年7月20日(星期四) 晚上10:18 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [mkang315/CST-YOLO] When I execute train.py I get the following error: NameError: nane 'myModel' is not defined (Issue #1) @.***作者提到的结果 您使用的是哪个数据集？您的数据集包括小对象吗？你的运行环境是怎样的？ — 直接回复此邮件，在GitHub上查看，或者取消订阅. @.与&gt;. Is your dataset publicly available? Or you could send it to me. CST-YOLO aims to blood cell detection. It isn't very strange that the performance of CST-YOLO is worse than YOLOv7 on other datasets. Also, our running environments are different from yours. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
Please send the download link (e.g. pan.baidu.com) to ***@***.*** Or you could add me as contacts on QQ. My QQ account is 365310768.  Is the dataset annotated manually? Have you divided the train and test sets? I'll evaluate CST-YOLO and YOLOv7 and find the reason why not effective on your dataset.
